ecommerce_project:
  outputs:
    dev:
      type: snowflake
      account: your-account  # Retirez "https://" et ".snowflakecomputing.com"
      user: your-username
      password: your-password  # Vérifiez que le mot de passe est valide
      role: ACCOUNTADMIN        # À remplacer par un rôle moins permissif si possible
      warehouse: COMPUTE_WH
      database: E_COMMERCE_DB
      schema: RAW
      threads: 4                # Augmentez ce nombre pour optimiser les performances
  target: dev